config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games do
    collection do
      patch :join_game
    end
    post 'take_card', on: :member
    post 'take_multiple_cards', on: :member
    post 'hand_to_market', on: :member
    post 'trade_in_tokens', on: :member
    post 'create_player', on: :member
    post 'take_all_camels', on: :member
    post 'multiple_cards_to_market', on: :member
  end
    # get 'games/hand', to: 'games#hand'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"
end

app/models/game.rb
class Game < ApplicationRecord
  attr_accessor :current_player
  has_many :players
  # accepts_nested_attributes_for :players, allows you to create a game and its players in one go and is normally used in conjunction with fields_for in the view.
  accepts_nested_attributes_for :players
  has_many :cards
  has_many :bonus_tokens
  has_many :tokens
  has_one :market
  has_one :discard_pile

  after_create_commit -> { broadcast_prepend_to "games", partial: "games/new_game", locals: { game: self }, target: "games" }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:create_player, :join, :change_turn, :show, :take_card, :refresh_market, :take_multiple_cards, :hand_to_market, :trade_in_tokens, :calculate_bonus_tokens, :end_turn, :take_all_camels, :hand_to_discard_pile, :game_over, :multiple_cards_to_market, :high_value_trade_in, :setup_game, :players_details]
  before_action :set_current_player, only: [:change_turn, :show, :trade_in_tokens, :multiple_cards_to_market, :take_multiple_cards, :take_card, :take_all_camels, :calculate_bonus_tokens, :update_card_ids, :turn_check]
  before_action :players_details, only: [:join, :show, :trade_in_tokens, :high_value_trade_in, :take_card, :take_all_camels, :update_card_ids, :multiple_cards_to_market, :take_multiple_cards, :calculate_bonus_tokens, :turn_check]
  before_action :turn_check, only: [:take_card, :take_all_camels, :take_multiple_cards, :trade_in_tokens, :hand_to_market, :multiple_cards_to_market]
  before_action :game_over_check, only: [:take_card, :take_all_camels, :take_multiple_cards, :trade_in_tokens, :hand_to_market, :multiple_cards_to_market]

  def index
    # I need to render this message as part of the link back to home page instead of the index. I need to overwrite the ingame messages with the general game message.
    # general_game_message("Welcome to Jaipur. Enter the game id to start playing or create a new game.")
    # I can still use the below in the index to display other games
    @games = Game.order(created_at: :desc).limit(5)
    @game = Game.new
  end

  def new
    @games = Game.order(created_at: :desc).limit(5)
    puts "Creating new game"
    @game = Game.new
  end

  def create
    if current_user == nil
      general_game_message("You must be logged in to create a game")
      return
    end
    puts "in create method"
    @games = Game.order(created_at: :desc).limit(5)
    @game = Game.new
    if @game.save
      market = Market.create!(game: @game)
      puts "Market created with id #{market.id}"
      discard_pile = DiscardPile.create!(game: @game)
      puts "Discard pile created with id #{discard_pile.id}"
      seed_cards(@game)
      puts "Cards seeded"
      seed_tokens(@game)
      puts "Tokens seeded"
      seed_bonus_tokens(@game)
      puts "Bonus tokens seeded"
      populate_market(@game)
      puts "Market populated"
      puts "creating players"
      2.times { @game.players.create }
      puts "players created"
      populate_initial_hands(@game.players.first, @game.players.second)
      puts "Initial hands populated"
      initialise_scores(@game.players.first, @game.players.second)
      puts "Scores initialised"
      puts "assigning current player"
      @game.update!(current_player_id: @game.players.first.id)
      puts "current player assigned"
      puts "Game setup complete"
      IndexUpdatesChannel.broadcast_to("index_updates", { message: "New game created" })
      # GameUpdatesChannel.broadcast_to(@game, { message: "New game created" })
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to games_path }
      end
    else
      puts "Game creation failed"
      @game = Game.new
      render :new
    end
  end

  def join_game
    puts "in update method"
    # if @game == nil
    #   redirect_to action: :index
    #   return
    # end
    id = params[:game_id]
    @game = Game.find(id)
    player = @game.players.find_by(user: nil)
    if player
      player.update!(user: current_user, name: current_user.email)
      redirect_to game_path(@game)
    else
      flash[:alert] = "Game is full"
      redirect_to games_path
    end
  end

  def change_turn
    puts "Changing turn"
    @current_player = @current_users_player.id == @game.players.second.id ? @game.players.first : @game.players.second
    @game.update!(current_player_id: @current_player.id)
    refresh_market()
    name = @current_player.name
    GameUpdatesChannel.broadcast_to(@game, { redirect: game_path(@game) })
    render_game_and_message()
    puts "Turn changed"
  end

  def show
    @game = Game.find(params[:id])
    @market_tokens = @game.market.tokens
    puts "Showing game"
    if game_over()
      final_scoring()
    end_turn()
    else
    general_game_message("#{@current_player.name}'s turn")
    end
  end

  def final_scoring
    @player1, @player2 = @game.players.order(:id)
    player1_token_total = @player1.tokens.sum(:value)
    puts "Player 1 token total: #{player1_token_total}"
    player2_token_total = @player2.tokens.sum(:value)
    puts "Player 2 token total: #{player2_token_total}"
    player1_bonus_token_total = @player1.bonus_tokens.sum(:value)
    puts "Player 1 bonus token total: #{player1_bonus_token_total}"
    player2_bonus_token_total = @player2.bonus_tokens.sum(:value)
    puts "Player 2 bonus token total: #{player2_bonus_token_total}"
    player1_herd_total = @player1.cards.where(card_type: "Camel").count
    puts "Player 1 herd total: #{player1_herd_total}"
    player2_herd_total = @player2.cards.where(card_type: "Camel").count
    puts "Player 2 herd total: #{player2_herd_total}"
    camel_bonus = player1_herd_total > player2_herd_total ? 'player1' : 'player2'
    player1_total = player1_token_total + player1_bonus_token_total + (player1_herd_total > player2_herd_total ? 5 : 0)
    player2_total = player2_token_total + player2_bonus_token_total + (player2_herd_total > player1_herd_total ? 5 : 0)
    @player1.update!(score: player1_total)
    @player2.update!(score: player2_total)
    if player1_total == player2_total
      winner = "It's a draw! No one"
    else
    winner = player1_total > player2_total ? @player1.name : @player2.name
    end
    general_game_message("Game over! #{@player1.name} scored #{player1_total} points. #{@player2.name} scored #{player2_total} points. #{winner} wins!")
  end

  def game_over
    puts "Checking if game is over"
    @player1, @player2 = @game.players.order(:id)
    cards_left = @game.cards.where(player_id: nil, market_id: nil, discard_pile_id: nil)
    puts "Cards left: #{cards_left.count}"
    condition1 = cards_left.count < 5
    goods_count = @game.market.tokens.where(token_type: ["Leather", "Spice", "Cloth", "Silver", "Gold", "Diamond"]).group(:token_type).count.values
    empty_tokens = goods_count.select { |token| token > 0 }
    condition2 = empty_tokens.length <= 3
    if condition1 || condition2
      final_scoring()
      puts "Game over"
      return true
    else
      return false
    end
  end

  def refresh_market
    puts "Refreshing market"
    while @game.market.cards.count < 5
    card = Card.where(game: params[:id], player: nil, market: nil, discard_pile: nil).sample
    break if card.nil?
    card.update!(market_id: @game.market.id)
    @game.market.cards << card if card
    end
    puts "Market refreshed"
  end


  def update_card_ids(card)
    puts "Updating card ids"
    puts card.inspect
    card.update!(market_id: nil, player_id: @current_users_player.id)
    puts card.inspect
    puts "Card ids updated"
  end

  def update_token_ids(token)
    token.update!(player_id: @current_player.id, market_id: nil)
  end

  def reset_trade_counter
    @current_users_player.update!(trade_counter: 0)
  end

  def calculate_bonus_tokens(total_trade_counter)
    puts "Calculating bonus tokens again"
    puts "Total trade counter: #{total_trade_counter}"
    puts "Current player trade counter: #{@current_users_player.name}"

    if total_trade_counter == 5
      bonus = @game.market.bonus_tokens.where(bonus_token_type: "trade_five_tokens").first
      bonus.update!(player_id: @current_users_player.id, market_id: nil)
    elsif total_trade_counter == 4
      bonus = @game.market.bonus_tokens.where(bonus_token_type: "trade_four_tokens").first
      bonus.update!(player_id: @current_users_player.id, market_id: nil)
    elsif total_trade_counter == 3
      bonus = @game.market.bonus_tokens.where(bonus_token_type: "trade_three_tokens").first
      bonus.update!(player_id: @current_users_player.id, market_id: nil)
    else
      return
    end
  end

  def hand_to_market()
    if @game.market.cards.count == 5
      change_turn()
    else
    card = Card.find(params[:card_id])
    card.update!(market_id:@game.market.id, player_id: nil)
    render_game_and_message()
    end
  end

  def multiple_cards_to_market()
    card_ids = params[:player_card_ids]
    camels_to_exchange = card_ids.select { |card_id| Card.find(card_id).card_type == "Camel" }
    goods_to_exchange = card_ids.select { |card_id| Card.find(card_id).card_type != "Camel" }
    balance = @current_players_cards.count - goods_to_exchange.count
    if card_ids.nil?
      render_game_and_message("You must choose at least one card to exchange")
      return
    elsif card_ids.length + @game.market.cards.count > 5
      render_game_and_message("You cannot exchange more cards than there are spaces in the market")
      return
    elsif balance > 7
      render_game_and_message("You cannot have more than 7 cards in your hand")
      return
    end
    if @game.market.cards.count == 5
      render_game_and_message("Market is full, take cards from market first")
      else
        for card_id in card_ids
          card = Card.find(card_id)
          card.update!(market_id:@game.market.id, player_id: nil)
        end
        if @game.market.cards.count < 5
          render_game_and_message("You must take cards from your hand to fill the market")
        else
        end_turn()
        end
    end
  end

  def hand_to_discard_pile(token)
    current_players_cards = @game.cards.where(player_id: @current_player.id)
    card_to_discard = current_players_cards.find { |card| card.card_type == token.token_type }
    if card_to_discard.nil?
      puts "No cards of that type"
      token.update!(player_id: nil, market_id: @game.market.id)  # return token to market
      change_turn()
    else

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_current_player.html.erb
<h1 class="text-2xl font-bold mb-4 text-white">Game Details in the partial - Current player: <%= @current_player.name %> - Score: <%= @current_player.tokens.sum(:value) %> Bonus: <%= @current_player.bonus_tokens.sum(:value)%></h1>

app/views/games/_five_games.html.erb
<%# <% games.each do |game| %>
  <%= form_with(model: game) do |form| %>
    <%= submit_tag "Join Game ##{game.id}" %>
  <% end %>
<% end %>

app/views/games/_flash_messages.html.erb
  <% if local_assigns[:notice].present? %>
    <p class="py-2 px-3 bg-black bg-opacity-70 mb-5 text-white font-m font-bold mt-2 rounded-lg inline-block animate-pulse" id="notice"><%= local_assigns[:notice] %></p>
  <% end %>

app/views/games/_form.html.erb
      <%= turbo_frame_tag 'new_game' do %>
        <%= form_for game, url: games_path, data: { turbo: false } do |f| %>
          <%= f.fields_for :players do |player_fields| %>
            <%= player_fields.label :name, class: "text-white font-bold rounded-md shadow-lg px-2 py-3 mx-1 bg-black bg-opacity-35 font-serif" %>
            <%= player_fields.text_field :name, class: "bg-white bg-opacity-60 rounded-lg transform transition duration-500 ease-in-out hover:bg-white shadow-md" %>
          <% end %>

          <div class="flex justify-center">
            <%= f.submit "Start New Game", class: "rounded-lg py-3 px-5 bg-green-500 bg-opacity-80 text-white block font-medium rounded-lg my-10 transform transition duration-500 ease-in-out hover:scale-105 shadow-md" %>
          </div>
        <% end %>
      <% end %>

app/views/games/_game.turbo_stream.erb
<turbo-stream action="replace" target="game">
  <template>
    <%= render partial: "game", locals: { game: @game }, formats: [:html] %>
  </template>
</turbo-stream>

app/views/games/_game_updates.html.erb
  <turbo-frame id="game_updates">
    <% if local_assigns[:game_notice].present? %>
      <p class="py-2 px-3 bg-black bg-opacity-70 mb-5 text-white font-m font-bold mt-2 rounded-lg inline-block animate-pulse" id="game_notice"><%= local_assigns[:game_notice] %></p>
    <% end %>
  </turbo-frame>

app/views/games/_hand.html.erb
  <div class="w-full sm:p-4 border-2 border-gray-500">
      <div class="justify-around items-center">

<div class="flex">
        <% @current_players_cards.each do |card| %>
          <div class="relative border-2 border-gray-500 w-16 h-24 sm:w-32 sm:h-48 rounded-md shadow-md bg-white p-1 sm:p-2 transform transition duration-500 ease-in-out hover:scale-105 shadow-obvious">
            <div class="w-full h-full relative">
              <div class="absolute inset-0 bg-cover bg-center rounded-md" style="background-image: url(<%= asset_path "#{card.card_type}.jpg" %>);">
              </div>
              <div class="hidden sm:block relative text-center text-xl font-bold bg-white bg-opacity-40 font-serif">
                <%= card.card_type %>
              </div>
            </div>
            <%= check_box_tag 'player_card_ids[]', card.id, false, class: "border-1 border-gray-700 p-1 rounded-md multi-card-select absolute top-1 left-1", style: "display: none;", data: {multi_select_target: "playerCheckbox"}  %>
          </div>
        <% end %>
</div>

        <div class="flex sm:items-center flex-wrap border-2 border-gray-500 w-full h-22 sm:h-24 rounded-md shadow-lg py-2">
          <% @current_players_herd.each do |camel| %>
            <div class="border-2 border-gray-500 w-6 h-6 sm:w-12 sm:h-12 rounded-md shadow-lg bg-white p-1 m-1 transform transition duration-500 ease-in-out hover:scale-105 shadow-md animate-bounce">
              <div class="absolute inset-0 bg-cover bg-center rounded-md" style="background-image: url(<%= asset_path "camel_selfie.jpg" %>);">
              </div>
            </div>
            <%= check_box_tag 'player_camel_ids[]', camel.id, false, class: "border-1 border-gray-300 rounded-md multi-card-select", style: "display: none;" , data: {multi_select_target: "playerCheckbox"}  %>
          <% end %>
        </div>
    </div>

  </div>

app/views/games/_new_game.html.erb
<turbo-stream action="prepend" target="games">
  <template>
    <turbo-frame id="game_123">
      <div class="game">
        <h2>Game <%= game.id %></h2>
    </turbo-frame>
  </template>
</turbo-stream>

app/views/games/_turbo_stream_action.turbo_stream.erb
<%= turbo_stream.replace 'games' do %>
  <%= render partial: 'games/five_games', locals: { games: games } %>
<% end %>

app/views/games/create_player.turbo_stream.erb
<turbo-stream action="replace" target="game">
  <template>
    <%= render partial: 'game', locals: { game: @game } %>
  </template>
</turbo-stream>

app/views/games/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Show this game", @game, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/index.html.erb
<div data-controller="index-updates-subscription">
  <div class="h-screen w-full p-4">
    <%# <h1 class="font-bold text-4xl text-white bg-black bg-opacity-30 p-2 w-1/4">Jaipur</h1> %>
    <div class="flex justify-center mt-6">
    <%= button_to 'New Game', games_path, method: :post, class: 'p-4 rounded-md bg-green-400 mx-4 font-bold text-gray-700 hover:bg-green-500 active:transform transition duration-500 ease-in-out active:scale-105 shadow-md active:bg-green-700' %>
    <%# <%= turbo_frame_tag 'new_game', src: new_game_path %>
  <div class="bg-white bg-opacity-50 rounded-lg p-2">
    <turbo-frame id="games">
      <%= turbo_stream_from "games" %>
    </turbo-frame>
  <%= form_with(url: join_game_games_path, method: :patch, data: { turbo: false }) do |form| %>
    <%= form.label :game_id, "Game ID", class: "text-gray-700 font-poppins font-bold" %>
    <div >
    <%= form.text_field :game_id, placeholder: "Enter Game ID...", class: "border-2 border-gray-500 p-1 rounded-md", required: true %>
    </div>
    <%= form.submit "Join Game", class: "my-2 p-2 rounded-md bg-green-400 text-gray-700 hover:bg-green-500 active:transform transition duration-500 ease-in-out active:scale-105 shadow-md active:bg-green-700 font-bold" %>
  <% end %>
  </div>

</div>
  <div class="flex justify-center w-full h-full items-center">
    <div class="w-3/4 bg-black bg-opacity-40 rounded-md">

      <div class="flex justify-center">
        <button id="toggleButton", class="rounded-lg py-3 px-5 bg-blue-500 bg-opacity-80 text-white block font-medium rounded-lg my-5 transform transition duration-500 ease-in-out hover:scale-105 shadow-md w-3/4 font-serif" onclick="toggleCollapsible()">
        Toggle Gameplay Instructions
        </button>
      </div>

        <div id="collapsible" class="w-full bg-black bg-opacity-40 text-white font-serif mt-2 overflow-auto transition-max-height duration-700 ease-in-out" style="max-height: 0vh;">
          <div class="flex justify-center font-bold my-4">
            <h2>Welcome to Japuir! The digital adaptation of the two-player card game by Sebastien Pauchon.</h2>
          </div>
          <div class="flex justify-center font-bold my-4 ">
            <h3>How to Play Jaipur</h3>
          </div>
          <div class="px-12">
            <div class="flex justify-center">
            <p>Jaipur is a fast-paced card game, a blend of tactics, risk and luck. On your turn, you can either take or sell cards. If you take cards, you have to choose between taking all the camels, taking one card from the market, or swapping 2-5 cards between the market and your cards. After your chosen action, play will automatically pass to the other player.</p>
          </div>


            <div class="flex justify-center font-bold my-2">
            <h3>Taking Cards</h3>
            </div>
            <p>If you choose to take cards you can do one of the following:</p>
            <ul>
              <li style="list-style-type: disc">Take one single goods card, as long as it doesn't take you over seven cards in your hand by clicking on it. It will be replaced with the top card from the draw deck automatically.</li>
              <li style="list-style-type: disc">Take the goods cards you want from the market into your hand and exchange them with goods from your hand and/or your camel herd. You many never finish with more than seven cards in your hand. Click first on "take multiple cards", click the checkboxes of the cards you'd like to take, and then click submit and the cards will be moved to your hand. Next click on "cards to market"and select the cards and/or camels that you'd ike to exchange from your hand, and then click submit. The cards/camels from your hand will populate the market. Note: you must replace the cards you take. The cards you take cannot be camels (see action below).</li>
              <li style="list-style-type: disc">Take all the camels and add them to your herd.</li>
            </ul>
            <div class="flex justify-center font-bold my-2">
            <h3>Selling Cards</h3>
            </div>
            <p>Choose a type of card you are going to sell by clicking on one of the goods in the market and the corresponding cards will be taken from your hand as payment. If you sold three or more goods, you will also automatically recieve a bonus token matching the size of your trade. NOTE: You are restricted to selling a minimum of two diamonds, gold or silver at a time.</p>
            <div class="flex justify-center font-bold my-2">
            <h3>Round End</h3>
            </div>
            <p>The round ends when either three goods token stacks are depleted. Or if there are no cards left in the draw pile while trying to fill the market.</p>
            <div class="flex justify-center font-bold my-2">
            <h3>Scoring</h3>
            </div>
            <p>At the end of the round, the player with the most camels in their herd receives the camel token, worth five rupees.</p>
            <p>The richer player (with the most Rupees) gets a Seal of Excellence and wins.</p>
            </div>
          </div>
        </div>
    </div>
</div>
</div>



<script>
  function toggleCollapsible() {
    console.log("toggleCollapsible");
    const collapsible = document.getElementById('collapsible');
    if (collapsible.style.maxHeight === '50vh') {
      collapsible.style.maxHeight = '0px';
    } else {
      collapsible.style.maxHeight = '50vh';
    }
  }

    document.addEventListener("turbolinks:load", function() {
    const form = document.querySelector('form');
    form.addEventListener('submit', function(event) {
      console.log('Form submitted');
      event.preventDefault(); // Remove this line if you want the form to submit
    });
  });
</script>

app/views/games/new.html.erb
<div class="mx-auto md:w-2/3 w-full">


  <%= render "form", game: @game %>

  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/show.html.erb
<div data-controller="game-updates-subscription" data-game-updates-subscription-game-id="<%= @game.id %>">
  <div class="flex self-center mx-auto w-screen sm:w-3/4">
    <div class="w-full rounded-md sm:p-5 relative" style="background-image: url(<%= asset_path 'table.jpg' %>); background-position: center; background-repeat: no-repeat; background-size: cover;">
      <div class="absolute inset-0 bg-green-600 opacity-10" style="pointer-events: none;"></div>
      <%= render partial: 'game', formats: [:html] %>
    </div>
  </div>
</div>